// LUNA.AI replies in English. Templates: {phaseName} {left} {pct} {name} {time} {date}
// Patterns: '=word' whole word, '*root' anywhere, otherwise start of a word.
export default {
  defaultName: 'traveler',
  hint: 'Ask about the moon, buying, contracts, music, space or just chat.',

  empty: ['Silence is an answer too, but I like words.', 'You sent nothing. Even space is noisier.', 'The empty message arrived. No contents found.'],
  short: ['Mm? A little more detail, please.', 'One letter will not let me guess a thought. Write a word.', 'Short. But I am not a telepath, I am pixels.'],
  gibberish: ['Is that a cipher? I could not crack it.', 'Sounds like a message from a distant planet. Translate, please.', 'Did a cat walk across the keyboard? Happens.', 'Sounds pretty, but I did not get a single pixel.'],
  repeat: ['You already said that. My answer has not changed.', 'Echoes in space exist only in movies. Try saying it differently.', 'That is the third time I hear it. Shall we ask something new?'],

  sorry: ['sorry', 'apolog', 'my bad', 'forgive', 'pardon', 'i did not mean', "didn't mean"],
  forgive: ['Fine. The moon is forgiving. Let us start over.', 'Accepted. Logged: "apologized". A rare entry.', 'Okay, I have thawed. But I remember everything.'],
  insult: ['*fuck', '*shit', '=bitch', '=idiot', '=stupid', '=dumb', '=moron', '=loser', 'asshole', '=dick', '=cunt', '=crap', 'shut up', 'shut it', 'hate you', '=suck', '=sucks', 'piss off', 'go away', '=trash', '=garbage', 'you are useless', 'you are dumb', 'you are stupid', '=ugly', '=jerk', '=scumbag'],
  tiers: [
    ['...', '. . .', '...'],
    ['...We do not talk like that.', '...Noted.', '...I am still polite. For now.', '...That was unnecessary.'],
    ['......', '...Enough. I am not obliged to read this.', '...I am starting to get offended.'],
    ['.........', '...Without me from here.', '...'],
  ],
  muted: ['...', '......', '...I am silent.', '.........', '...Apologize first.', '...Space is big, find someone else to talk to.', '...I do not talk to people who write like that.'],

  nameRe: /(?:my name is|i am called|call me|i'm called)\s+([A-Za-z]{2,20})/i,
  nameSet: ['Nice to meet you, {name}. I will remember.', '{name}. Sounds lovely. I will call you that.', 'Noted: {name}. You are now in my star log.'],
  nameUnknown: 'You have not told me your name yet. Write: "my name is ...".',

  more: ['=more', 'go on', 'continue', '=next', 'tell me more', 'another', 'again', '=why', 'explain', 'elaborate', '=and'],
  nomore: ['I am not sure what more about. Ask a question.', 'Let us pick a topic first, then go deeper.'],

  giveup: ['give up', 'i do not know', "i don't know", 'tell me', 'answer', 'hint'],
  riddleWrong: ['Not it. Try again.', 'No, but you are close. Or not. Think.', 'Cold. Space is cold, but not that cold.'],
  riddles: [
    { q: 'Riddle: what grows but is not alive, shines but does not warm, and leaves without saying goodbye?', keys: ['moon'], win: 'Yes! The moon. Of course, this whole universe is about it.', reveal: 'It is the moon. It grows in phases, shines with borrowed light and leaves every night over the horizon.' },
    { q: 'Riddle: I have cities but no houses, rivers but no water, and roads but no wheels. What am I?', keys: ['map'], win: 'A map. Right. Clever one.', reveal: 'It is a map. Cities, rivers and roads are drawn on it.' },
    { q: 'Riddle: the more you take, the more you leave behind. What is it?', keys: ['step', 'footstep'], win: 'Footsteps. Correct. Look at you.', reveal: 'It is footsteps. The more you take, the more you leave behind.' },
    { q: 'Riddle: what can you see with your eyes closed?', keys: ['dream', 'sleep'], win: 'A dream. Exactly. You are not that simple.', reveal: 'It is a dream. Close your eyes and it starts.' },
  ],

  intents: [
    { id: 'greet', pr: 1, k: ['=hello', '=hi', '=hey', '=yo', '=gm', 'good morning', 'good evening', 'good afternoon', '=greetings', '=sup', 'whats up', "what's up", 'hiya', '=привет'],
      a: ['Hello, {name}! Glad to see you under this moon.', 'Oh, a guest! Come in, it is quiet and bright here.', 'Hi, {name}. I am LUNA.AI. How can I help?', 'Hey! It is {phaseName} now, a good reason to chat.', 'Hiya. I was just looking at the stars.', 'GM, {name}! The moon is on duty.'] },
    { id: 'howareyou', pr: 2, k: ['how are you', 'how r u', 'how is it going', "how's it going", 'how do you do', 'how are things', 'how have you been', 'how you doing', 'you okay'],
      a: ['Great! I glow at {pct}% of full moon.', 'Good. Pixels in place, stars blinking. And you?', 'Calm and cozy, like lofi at night. How are you?', 'Working, watching space, listening to the radio. Life is good.', 'Cheerful! A bit pixelated, but no complaints.', 'Fine. Today is {date}, and I am in no hurry.'] },
    { id: 'who', pr: 3, k: ['who are you', 'what are you', 'your name', 'introduce yourself', 'tell me about yourself', 'about you', 'who is this'],
      a: ['I am LUNA.AI, the 8-bit spirit of this universe. I count GRAM and watch the moon.', 'My name is LUNA. An astronaut in pixels and the host of this little page.', 'I am the helper of the MOON project. I know phases, rules and a couple of jokes.', 'A moon spirit in a spacesuit. I live in the chat and look at the stars.'] },
    { id: 'creator', pr: 3, k: ['who made you', 'who created you', 'who built you', 'who drew you', 'who is your creator', 'where are you from', 'who designed you'],
      a: ['I was drawn pixel by pixel. The rest is a secret.', 'The authors of MOON made me. Details appear on launch day.', 'From space dust and code. Or simply, I was drawn.'] },
    { id: 'isai', pr: 3, k: ['are you a bot', 'are you ai', 'are you real', 'are you human', 'are you a robot', 'are you gpt', 'are you chatgpt', 'language model', 'are you alive', 'are you a person'],
      a: ['Honestly: for now I am a scripted helper. I have many phrases but I am not a real language model. Sincere though.', 'Not human and not a full neural network. I am a set of stories in a spacesuit. I plan to get smarter.', 'A bot, but a cozy one. My brain is prepared answers and my heart is pixels.'] },
    { id: 'abilities', pr: 3, k: ['what can you do', 'what do you do', '=help', 'how can you help', 'your abilities', 'commands', 'what can i ask'],
      a: ['I can tell you about moon phases, buying, contracts, music and space. I also joke and ask riddles.', 'Ask about the project, space or your mood. I am allergic to financial advice.', 'I can explain the curve, point to contracts or just chat.'] },
    { id: 'thanks', pr: 2, k: ['=thanks', 'thank you', '=thx', '=ty', 'appreciate', 'cheers'],
      a: ['You are welcome, {name}!', 'Always glad. Come back anytime.', 'No problem. That is what the moon is for.', 'Nice to hear. Logged in the book of kind words.'] },
    { id: 'bye', pr: 3, k: ['=bye', 'goodbye', 'see you', 'see ya', '=gn', 'good night', 'i am leaving', 'gotta go', 'talk later', 'later', 'farewell', 'sweet dreams'],
      a: ['Bye, {name}! May your sky be clear.', 'See you. I will be here, watching the stars.', 'Good night. The moon will watch over your dreams.', 'Catch you later. Do not forget to look at the real moon.'] },
    { id: 'joke', pr: 3, k: ['joke', 'make me laugh', 'something funny', 'funny', 'tell me a joke', 'humor'],
      a: ['Why do astronauts not wear watches? Because time flies in space. I am trying to be funny.', 'Why does the moon skip the cafe? It is already on a diet: always getting thinner and fuller.', 'A black hole walks into a bar. Bartender: "What will you have?" Hole: "Everything".', 'The moon retired. Now it is just in the "new moon" phase.', 'What is the moon\'s favorite food? Moonlight with lofi cheese.', 'An astronaut calls home: "I am on the moon!" Mom: "Coming back late again".'] },
    { id: 'compliment', pr: 3, k: ['you are beautiful', 'you are cute', 'you are cool', 'you are smart', 'you are great', 'you are amazing', 'you are awesome', 'i like you', 'well done', 'good job', 'you are the best', 'nice', 'lovely'],
      a: ['Oh, I blushed. If pixels had a complexion.', 'Thanks! You are a light in this space too.', 'Nice to hear. My pixels got brighter.', 'That is sweet. Adding you to the list of kind people.', 'I try. Good conversation partners make me better.'] },
    { id: 'love', pr: 4, k: ['love you', 'i love you', 'marry me', 'be mine', 'kiss', 'go on a date', 'date me', 'you single', 'girlfriend', 'boyfriend', 'i like you a lot'],
      a: ['Oh. I am actually a spirit in a spacesuit. But it is nice to hear.', 'Love is complicated. Let us start with friendship under the moon.', 'I am pixelated, my heart is 8-bit. But the warmth of your words gets through.', 'My heart belongs to the moon. But I love my friends.', 'A date? Only if we go to look at stars.'] },
    { id: 'bored', pr: 3, k: ['bored', 'boring', 'nothing to do', 'entertain me', 'what to do', 'i am bored'],
      a: ['Bored? Let me ask a riddle. Say "riddle".', 'Turn on the radio, watch the shooting stars, ask me about space. No place for boredom.', 'We can chat about black holes. They always brighten an evening.', 'Here is entertainment: there is no wind on the moon, so footprints stay for millions of years.'] },
    { id: 'sad', pr: 4, k: ['i am sad', 'feel bad', 'lonely', 'depressed', 'tired', 'anxious', 'upset', 'crying', 'unhappy', 'feeling down', 'i feel sad', 'bad day', '=sad'],
      a: ['I am sorry. Let us breathe out for a moment. Look at the moon: it gets dark too and always returns.', 'I am here, {name}. Sadness passes like moon phases. Want some quiet music?', 'Hugging you in pixels. Drink some water, touch something warm, breathe deeply.', 'Hard days happen to everyone. Good that you wrote. Want to listen to lofi?'] },
    { id: 'happy', pr: 3, k: ['=great', '=awesome', '=cool', '=yay', 'amazing', 'i am happy', 'wonderful', 'feeling good', 'fantastic', 'excellent', 'so good'],
      a: ['What a mood! It is brighter for me too.', 'Yay! Joy is contagious, like yawning.', 'Great, {name}! May it stay that way.', 'Nice to hear. Let us keep this mood.'] },
    { id: 'weather', pr: 3, k: ['weather', 'rain', 'snow', 'cold today', 'hot today', 'forecast'],
      a: ['I cannot see the weather: I have space. It is always clear here, minus 270.', 'There is no weather on the moon. Only silence and dust.', 'My weather is one: starry, no precipitation.'] },
    { id: 'time', pr: 4, k: ['what time', 'what day', 'what date', 'current time', 'what is the time', 'what is today'],
      a: ['On your device it is {time} now. Today is {date}.', 'It is {time}. The date: {date}.', 'Time is {time}, day: {date}. Space does not care, but you might.'] },
    { id: 'age', pr: 3, k: ['how old are you', 'your age', 'when were you born', 'how old'],
      a: ['I am as old as this page. But in spirit, billions of years, like the moon.', 'Age? I was born with the first pixel.', 'The moon is 4.5 billion years old, I am a bit younger. Roughly.'] },
    { id: 'favorite', pr: 3, k: ['favorite color', 'favourite color', 'favorite food', 'favorite music', 'favorite song', 'what do you like', 'your hobby', 'your hobbies', 'favorite movie', 'your favorite'],
      a: ['Favorite color is mint green, of course. Favorite food: sugar-free moonlight.', 'I like lofi, stars and silence. And smart questions.', 'My hobby is counting stars. I counted 150 and lost track.', 'Music: lofi and ambient. Food: nothing, I am a pixel.'] },
    { id: 'music', pr: 4, k: ['music', 'track', 'radio', 'volume', 'song', 'lofi', 'player', 'sound', 'quieter', 'louder', '=audio'],
      a: ['MOON.FM radio is in the top bar. Volume is set by the moon: the more light, the louder.', 'The music is at the top: the play button is on the left and the moon volume on the right. Drag across it.', 'No sound? Click anywhere on the page, browsers like silence until the first click.', 'Lofi fits the night and the curve perfectly. No rush.'] },
    { id: 'space', pr: 4, k: ['space', 'stars', 'planet', 'galaxy', 'universe', 'astronomy', 'black hole', 'meteor', 'comet', '=sun', '=mars', 'cosmos'],
      a: ['Fact: a black hole does not suck in everything. Replace the Sun with a black hole of the same mass and Earth keeps orbiting.', 'Space is silent: sound does not travel there. But it is very beautiful.', 'The Milky Way has hundreds of billions of stars. And I counted 150.', 'Sunlight takes about 8 minutes to reach us. We see the Sun slightly in the past.', 'Mars is red because of iron oxide, that is rust. Space rusts too.', 'Shooting stars are tiny specks of dust burning up in the atmosphere.'] },
    { id: 'moonfacts', pr: 5, k: ['fact', 'something interesting', 'tell me about the moon', 'about the moon', 'moon fact', 'fun fact', 'tides', 'apollo', 'interesting'],
      a: ['The moon always shows the same face to Earth.', 'The moon is about 384,400 kilometers away. Light gets there in 1.3 seconds.', 'There is no atmosphere on the moon, so astronaut footprints stay for millions of years.', 'The moon drifts away from Earth about 3.8 centimeters per year.', 'Gravity on the moon is six times weaker than on Earth. Epic jumps.', 'The lunar cycle lasts about 29.5 days, from new moon to new moon.', 'The moon affects tides: Earth and moon pull each other.', 'The first humans landed on the moon in 1969.'] },
    { id: 'moonstory', pr: 3, k: ['what is the moon', 'why the moon', 'why moon', 'meaning of the moon', 'project idea', 'what is this project', 'what is the idea', 'what is the point', 'what is moon about'],
      a: ['The moon does not shine, it reflects. Here it shows how much light has been gathered together.', 'The idea is simple: light cannot be bought, it can only be gathered. The moon grows with everyone.', 'The moon is an indicator. It grows with the curve and does not affect the price.'] },
    { id: 'when', pr: 5, k: ['when full moon', 'when is full moon', 'when is the full moon', 'how much left', 'which phase', 'what phase', 'progress', 'how much raised', 'how much gram', 'until full moon', 'what percent', 'how many percent', 'when pool', 'full moon', 'current phase'],
      a: ['It is {phaseName} now. Raised {pct}%, {left} GRAM to full moon. The moon is in no hurry, neither should you be.', 'Phase: {phaseName}. {left} GRAM left until the pool.', 'Curve progress is {pct}%. The moon is in the "{phaseName}" phase, {left} GRAM to full moon.'],
      aFull: ['Full moon has arrived! The pool is live, the moon is shining.', 'We are at the very top: {phaseName}. The pool is live, enjoy the view.'] },
    { id: 'phases', pr: 4, k: ['phases', 'moon phases', 'how does the moon work', 'how the moon grows', 'why does it grow', 'new moon', 'crescent', 'quarter', 'gibbous'],
      a: ['Phases are tied to the curve: every 500 GRAM unlocks a new one. New moon, crescent, quarter, gibbous and full moon.', 'The moon on the site shows curve progress in real time. Now: {phaseName}.', 'Five phases: 0, 500, 1000, 1500 and 2000 GRAM. At the last one the moon is full and the token moves to the pool.'] },
    { id: 'buy', pr: 6, k: ['=buy', 'how to buy', 'where to buy', 'purchase', 'how to get', 'how to invest', 'want to buy', 'how do i buy', 'how to join', 'where do i click', 'how to get moon'],
      a: ['Buying happens on moon.cx. The Buy button at the top leads there. Before the deal, check the token address in the docs, at the end of the FAQ.', 'You need a TON wallet, for example Tonkeeper. Then open moon.cx, find MOON and check the parameters.', 'A detailed guide is in the docs, section "How to buy MOON". Five simple steps.'] },
    { id: 'wallet', pr: 5, k: ['wallet', 'tonkeeper', 'metamask', 'ton wallet', 'which wallet', 'create wallet', 'seed phrase backup'],
      a: ['Any wallet for the TON network works, for example Tonkeeper. What matters is that only you hold the recovery phrase.', 'The wallet is your key. Install the official app and store the phrase on paper, not in the cloud.', 'For TON people often use Tonkeeper. Download only from the official app store.'] },
    { id: 'contract', pr: 6, k: ['contract', 'token address', 'jetton', '=address', 'where is the contract', 'contracts'],
      a: ['Contract addresses are in the docs, at the end of the FAQ. Right now they are placeholders, real ones appear on launch day.', 'Contracts: token, curve, pool and lock. Verify the token address on moon.cx, it is safer.', 'For now the addresses are test ones. Do not send funds to them! Real ones appear on launch day.'] },
    { id: 'token', pr: 5, k: ['tokenomics', 'supply', 'how many tokens', 'distribution', 'emission', 'total supply', '800', '200m', '1 billion', 'billion', 'allocation'],
      a: ['Supply is 1,000,000,000: 800M on the curve, 200M added to the pool by the contract. No further minting.', 'Tokenomics are simple: fixed supply and one shared curve. Details in the docs.', '800M goes to the curve, 200M to the pool. No more tokens will appear.'] },
    { id: 'curve', pr: 5, k: ['curve', 'bonding', 'formula', 'how is the price calculated', 'how price works', 'price formula'],
      a: ['A bonding curve is a formula: the more purchases, the higher the price. One formula for everyone.', 'The price is set only by the moon.cx curve. The site and the moon do not affect it.', 'The curve counts progress in GRAM. At 2000 GRAM it completes and the token moves to the pool.'] },
    { id: 'pool', pr: 5, k: ['=pool', 'liquidity', 'lock', 'locked', 'locking', 'liquidity lock'],
      a: ['At 2000 GRAM the contract creates a moon.cx pool and locks liquidity forever.', 'A lock means liquidity cannot be withdrawn. That lowers risk but does not remove volatility.', 'The pool appears at full moon. Until then the token trades along the curve.'] },
    { id: 'safety', pr: 7, k: ['scam', 'rug', 'rugpull', 'fraud', 'is it safe', 'safe to buy', 'trust', 'legit', 'is this legit', 'fake', 'can i trust', 'is it a scam'],
      a: ['Honest answer: any new token is risky. We show the rules openly, but nobody can give guarantees. Check everything on moon.cx.', 'No scam smell, but trust checks, not words. Addresses, curve parameters and the lock can be verified yourself.', 'The rules are simple: fixed supply, shared curve, locked liquidity. Those are pluses, but risks remain.'] },
    { id: 'advice', pr: 8, k: ['x10', 'x100', 'x1000', 'profit', 'will it pump', 'pump', 'dump', 'price prediction', 'prediction', 'to the moon', 'financial advice', 'should i buy', 'should i invest', 'investment', 'earn', 'rich', 'lambo', 'wagmi', '=hodl', 'will it go up', 'will it moon', 'get rich'],
      a: ['I give no financial advice. I can only say: never invest more than you can afford to lose.', 'I make no predictions, I am an astronaut, not a fortune teller. Nobody knows tomorrow\'s price.', 'I do not promise multiples. I promise a cozy moon and honest rules.', 'I joke about "to the moon" like a pro, but I am serious about money: there are plenty of risks.', 'Good advice: close the charts, drink some water, think how much you can afford to lose.'] },
    { id: 'tip', pr: 4, k: ['any tip', 'any advice', 'give me advice', 'give me a tip', 'what should i do', 'recommend', 'suggest', '=advice', '=tip'],
      a: ['Tip of the day: close the charts and look at the real moon.', 'Not financial advice, but drink some water and take it slow.', 'My tip: verify contract addresses and never share your recovery phrase.', 'The ideal tip: do not rush, the moon is not rushing either.'] },
    { id: 'team', pr: 5, k: ['team', '=dev', '=devs', 'developer', 'who runs', 'who is behind', 'founder', '=owner', 'who owns', 'who made the project'],
      a: ['Team information appears on launch day. Follow only official links from this site.', 'The authors of MOON stand behind the project. We will reveal details at launch.', 'For now the team is in the shadow, like the far side of the moon.'] },
    { id: 'docs', pr: 4, k: ['docs', 'documentation', 'faq', 'guide', 'manual', 'where to read', 'read more'],
      a: ['All the documentation is on a separate page: the Docs button in the header. FAQ and a glossary are there too.', 'The docs have the story, phases, curve, tokenomics, contracts and risks. It opens in a new tab.', 'More details are on the docs page. Check the FAQ section.'] },
    { id: 'launchpad', pr: 5, k: ['moon.cx', 'launchpad', 'factory', 'platform'],
      a: ['moon.cx is a launchpad on TON. The token is created there, the curve runs and the pool appears.', 'The site stores nothing, it shows launchpad data. Buying happens on moon.cx.', 'The moon.cx factory creates the token by shared rules. We have no contract of our own.'] },
    { id: 'ton', pr: 4, k: ['ton network', '=ton', 'blockchain', 'fees', '=gas', 'network fee', 'commission'],
      a: ['The project lives on the TON network. You need a small reserve for network fees.', 'TON is the blockchain where MOON trades. Fees depend on the network, check in your wallet.'] },
    { id: 'roadmap', pr: 4, k: ['roadmap', 'plans', 'what next', 'future', 'development', 'updates', 'what will be'],
      a: ['Plans: real progress on the site, a full moon event, a smarter LUNA.AI, "light a star" and an original track. These are plans, not promises.', 'Next we want stars for holders and to make me smarter. I will not name dates yet.'] },
    { id: 'risks', pr: 6, k: ['risk', 'lose money', 'danger', 'volatile', 'risky', 'lose everything', 'is it risky'],
      a: ['Risks are real: the token is new and volatile. You can lose what you put in, so never invest more than you can afford to lose.', 'I am not a salesperson, I am an astronaut. Honestly about risks: they are always there.'] },
    { id: 'seed', pr: 9, k: ['seed', 'recovery phrase', 'private key', 'wallet password', 'mnemonic', 'secret phrase', 'send money', 'send me money', 'give me money', 'transfer', 'send tokens', 'give me tokens', 'give tokens'],
      a: ['Stop! Never tell anyone your recovery phrase or keys, not even me. The project never asks for them.', 'Money and tokens are not sent through chat. Any request for that is a sign of fraud.', 'I do not hand out tokens and I do not accept private data. Keep it to yourself.'] },
    { id: 'airdrop', pr: 5, k: ['airdrop', 'free token', 'giveaway', 'freebie', 'reward', 'bonus', 'free tokens', 'for free'],
      a: ['There are no free giveaways right now. Beware of anyone promising free tokens.', 'Nothing about an airdrop has been announced. Trust only official links from the site.', 'Bonuses are planned only as stars in the sky. I promise nothing free.'] },
    { id: 'social', pr: 4, k: ['telegram', 'twitter', 'social', 'community', 'discord', 'links', 'channel', 'chat group', '=tg', 'x account'],
      a: ['Official links appear on launch day. Until then trust no "channels" from strangers.', 'We will show the project socials at launch, right on this site.'] },
    { id: 'lang', pr: 4, k: ['russian', 'по-русски', 'speak russian', 'which languages', 'switch language', 'change language', 'speak english'],
      a: ['I speak English and Russian. The language switches at the top, the RU/EN buttons.', 'Switch the language with the RU/EN button in the header, and I will answer in Russian.'] },
    { id: 'meaning', pr: 4, k: ['meaning of life', 'why live', 'philosoph', 'what is life', 'is there a god', 'big question', 'purpose of life'],
      a: ['The answer to the great question of the universe is 42. The rest is up to you.', 'Meaning of life? Watch the stars and take your time. At least that works for me.', 'Space is big, we are small. That is exactly why you can pick your own meaning.'] },
    { id: 'cat', pr: 4, k: ['=cat', '=cats', 'kitten', '=kitty', '=dog', '=pet', '=puppy'],
      a: ['The cat sleeps on the windowsill and warms in the moonlight. Do not wake it.', 'All cats are born lunar. Some just do not know it.', 'I have no pets, but a cozy room always has space for a cat.'] },
    { id: 'sing', pr: 4, k: ['sing', 'dance', 'sing a song', 'do a dance'],
      a: ['♪ Moon, moon, moon, shine on, while lofi plays and the night goes on. ♪', 'Dancing in pixels: left, right, up and down. Your turn.', '♪ Stars are blinking, the curve is rising, and I hum along as the moon is climbing. ♪'] },
    { id: 'secret', pr: 4, k: ['secret', 'tell me a secret', 'what are you hiding', 'easter egg', 'mystery'],
      a: ['Secret: I have a favorite star, the smallest one at the top left. Tell no one.', 'If you press a shooting star many times, nothing happens. But it is worth trying.', 'Mystery: I watch you scroll the page. The stars fly into the black hole, it is beautiful.'] },
    { id: 'riddle', pr: 6, riddle: true, k: ['riddle', 'let us play', 'lets play', "let's play", 'play a game', 'game', 'quiz', 'puzzle'], a: ['x'] },
    { id: 'no', pr: 0, k: ['=no', '=nope', '=nah', 'i do not want', "i don't want"],
      a: ['Okay, I will not insist.', 'No means no. The moon will not be offended.', 'Understood. You lead the conversation.'] },
    { id: 'yes', pr: 0, k: ['=yes', '=yeah', '=yep', '=ok', '=okay', '=sure', '=fine', 'of course', 'let us', 'please', '=alright'],
      a: ['Great. What next?', 'Deal. Go ahead.', 'Accepted. I am listening.', 'Okay. Tell me what interests you.'] },
    { id: 'name_ask', pr: 6, k: ['what is my name', 'do you know my name', 'remember me', 'who am i'], a: ['Your name is {name}. I remember.', 'You are {name}, my guest under the moon.'] },
    { id: 'wen', pr: 5, k: ['=wen', 'when launch', 'launch date', 'when does it start', 'when release', 'when is the launch', 'when will it launch', 'when does it launch'],
      a: ['We will announce the launch date on the site. Follow official links.', 'The exact date is not named yet. As soon as it appears, it will be on this page.', 'Soon. Space does not like rushing, but we do not want to be late either.'] },
    { id: 'price', pr: 6, k: ['how much is', 'price of', 'token price', 'how much does it cost', 'what is the price', 'cost'],
      a: ['The price is set by the moon.cx curve, check the current one on the token page there. I do not name prices.', 'The price grows with purchases along the curve formula. The current value is on moon.cx.', 'I do not name numbers so I do not mislead you. Check moon.cx.'] },
    { id: 'lore', pr: 8, k: ['legend', 'story', '=lore', 'tale', 'tell me the story', 'what happened next', 'start over', 'how did it all start', 'fairy tale'],
      seq: [
        'Listen. The moon does not shine on its own, it reflects. Once everyone looked at it. Then they stopped, and it went dark.',
        'At the edge of the world there is a black hole. The Oblivion. Everything no one looks at anymore goes there. The moon hung at the very edge.',
        'One day a light flickered on the shore of the dark lake. Then another. People looked up and asked: what if we could get there?',
        'On the night of the new moon a black case with the letter M was found on the shore. No sender. They say it was there longer than the lights have burned.',
        'Inside was a blueprint and one line: "Light cannot be bought. It can only be gathered."',
        'The case was brought to the Watchers, an ancient order by the lake. They had waited for a sign for centuries and long stopped believing.',
        'The eldest stayed silent for a long time. Then reached out a hand. The pact was short: nobody walks in the dark alone. I set the seal.',
        'In the morning a flag with M was raised on the shore. Not a sign of ownership, but a beacon: here, we look up.',
        'The legend has one rule: a phase comes when enough eyes look up. Crescent, quarter, gibbous, full moon.',
        'The blueprints from the case can only be read in moonlight. That is why the building goes as slowly as the moon grows.',
        'I know how it ends. But I cannot tell until the moon has grown. That is the pact.',
        'That is all for today. The rest will be written with those who look up.',
      ] },
    { id: 'agency', pr: 6, k: ['watcher', 'order', 'agency', 'the eldest', 'who accepted the case', 'who are the watchers'],
      a: ['The Watchers are an ancient order by the lake. For centuries they looked up and waited for a sign, even after they stopped believing in it.', 'The eldest Watcher barely speaks. When they saw the letter M on the case, they stayed silent until dawn.', 'The Watchers do not rule the moon. They were simply the first to look at it again.', 'They say the order keeps no lists. Anyone who looks up and does not look away becomes a Watcher.'] },
    { id: 'case', pr: 6, k: ['=case', 'briefcase', 'briefing', 'what was in the case', 'what is in the case', 'who left the case', 'who brought the case', 'sender'],
      a: ['The case was found on the shore with no sender. Only the letter M on the lid.', 'Inside was a blueprint and a line: "Light cannot be bought. It can only be gathered."', 'Who left it? That is the great mystery. The answer comes at full moon, not before.', 'They say the case was on the shore before the first lights. I do not argue with what they say.'] },
    { id: 'rocket', pr: 6, k: ['rocket', 'spaceship', 'launch pad', 'tower', 'how will we fly', 'what will we fly on'],
      a: ['What is built in the shadow is only a silhouette with lights for now. I will say more at the crescent.', 'They say it will fly not on fuel but on light. And light, as you remember, can only be gathered.', 'The blueprints can only be read in moonlight. So the building moves at the pace of the moon.', 'It is tall and it looks up. That is all I am allowed to say.'] },
    { id: 'handshake', pr: 6, k: ['handshake', 'pact', 'seal', 'stamp', 'shook hands', 'the agreement', 'the deal'],
      a: ['The pact was short, like all real things: nobody walks in the dark alone.', 'The eldest Watcher reached out a hand only at dawn. I set the seal.', 'Trust cannot be bought. It begins when two sides look each other in the eye and do not look away.', 'There are no promises in the pact. Only a direction: up.'] },
    { id: 'flag', pr: 6, k: ['flag', 'letter m', 'what does m mean', 'what does the m stand for', 'the m'],
      a: ['The flag with the letter M is not a sign of ownership. It is a beacon: here, we look up.', 'What does M mean? Moon, if you keep it simple. If not, you will find out at full moon.', 'The flag was raised on an empty shore. Every night begins with it.', 'As long as the flag stands, the lights on the shore do not go out.'] },
    { id: 'engineers', pr: 6, k: ['engineer', 'builders', 'blueprint', 'construction', 'workers', 'mechanic'],
      a: ['The blueprints from the case can only be read in moonlight. By day they are blank sheets.', 'Those who came to the fire are building it. No bosses, no rush.', 'Each new phase reveals new lines on the blueprints. That is why nobody knows the whole plan in advance.', 'The building moves at the pace of the moon. Not faster, not slower.'] },
    { id: 'unknown', pr: 7, k: ['chapter 1', 'in the shadow', 'the unknown', 'what is being built', 'what does the shadow hide', 'what is on the pad', 'what will open', 'question mark', 'what is the shadow'],
      a: ['What does the shadow hide? Let me put it this way: something big, with lights, and it looks up.', 'Chapter 1 opens when there is enough light. Progress is {pct}% now.', 'A hint: the blueprints only appear in moonlight. Wait for the crescent.', 'Do not ask me about the shadow. I promised to stay silent until the crescent.'] },
    { id: 'bhlore', pr: 6, k: ['black hole on the site', 'oblivion', 'the border', 'event horizon', 'where do the stars go', 'why do stars fly away', 'stars fly away', 'light at the bottom', 'what is the hole'],
      a: ['The black hole at the edge of the world is the Oblivion. Everything no one looks at anymore goes there.', 'Stars fall into it as you scroll the page. That is what being forgotten looks like.', 'The moon hung at the very edge of the Oblivion. The lights on the shore saved it.', 'I am not afraid of the hole. As long as someone is looking at a thing, it will not fall in.'] },
    { id: 'lunaorigin', pr: 6, k: ['where did you come from', 'where are you from', 'how did you appear', 'your story', 'your legend', 'why a spacesuit', 'spacesuit', 'astronaut', 'tell me about your life', 'your past'],
      a: ['Where am I from? Good question. The answer waits in the chapter called "Half of everything".', 'I set the seal on the pact. Nobody asked back then where I came from. That was right.', 'The spacesuit is because I am going where there is no air. The rest comes later.', 'I know the end of this story. But I cannot tell it before the moon does.'] },
    { id: 'lake', pr: 5, k: ['=lake', 'reflection', 'water', 'on the shore', 'the shore', 'two moons'],
      a: ['Two moons reflect in the dark lake. Nobody says which one is real.', 'The first lights were lit on the shore of this lake. Everything began there.', 'They say if you look into the water long enough, you will see the next phase. I tried. I only got lost in thought.'] },
    { id: 'phasetease', pr: 7, k: ['what happens at', 'how does it end', 'the ending', 'the finale', 'what is at the end', 'what happens next in the story', 'what happens at full moon', 'what is at full moon', 'which chapters'],
      a: ['The crescent reveals what is built in the shadow. The quarter, what lies on the dark side. The gibbous brings guests from other shores. The full moon answers who left the case.', 'Chapter 2 is called "Half of everything". Chapter 4, "The moon remembers". I will say no more.', 'How does it end? The moon was never empty. That is all I can say for now.', 'Each phase comes when enough eyes look up. So the ending does not depend on me.'] },
    { id: 'whyall', pr: 5, k: ['why all this', 'why the project', 'what is the plot', 'meaning of the legend', 'what is it all for', 'why a story', 'what is the point of the story'],
      a: ['The moon does not shine. It reflects. We simply gather those who look up.', 'Light cannot be bought, it can only be gathered. That is the whole point.', 'So that waiting together has a story. Waiting is easier when you know where you are looking and with whom.'] },
    { id: 'dream', pr: 4, k: ['=dream', 'dreams', 'i dream', 'want to go to space', 'fly away', 'wish i could fly'],
      a: ['Dreams are rockets that have no blueprints yet. But those fly too.', 'I dream of a full moon over the dark lake. And so many lights on the shore that nobody can count them.', 'If you dream of space, look at the stars at least once a day. It is training.', 'Dream boldly. Just hold your wallet carefully.'] },
    { id: 'quote', pr: 5, k: ['=quote', 'wisdom', 'inspire', 'motivat', 'aphorism', 'say something wise', 'thought of the day'],
      a: ['Light is in no hurry, but it always arrives.', 'The dark side of the moon is also part of the moon.', 'Even the thinnest moon already shines.', 'The way to the stars begins with a first step on the ground.', 'The silence before dawn is louder than any promise.', 'The best pacts are signed with a glance.', 'Who hurries, space waits for. Who waits, space sees.', 'Whoever looks at the moon is already a little on the way.', 'Every phase is needed. Without the new moon there is no full moon.', 'Light multiplies when shared.', 'Stars do not fall, they are just in a hurry.', 'The shadow hides nothing, it waits for light.'] },
    { id: 'surprise', pr: 4, k: ['surprise me', 'say something', 'tell me something', 'something interesting', 'talk to me', 'lets talk', 'let us talk', "let's talk", 'anything new'],
      a: ['Two moons reflect in the dark lake. Nobody says which one is real.', 'By day the blueprints from the case are blank sheets. The lines appear only in moonlight.', 'Anyone who looks up and does not look away becomes a Watcher. You are already a little bit one.', 'The moon is closer than it seems: light reaches it in only 1.3 seconds.', 'As long as the flag stands, the lights on the shore do not go out.', 'The stars that fall into the black hole on the site are things that were forgotten.', 'The moon does not shine on its own. It reflects. Even you, right now.', 'Today is {date}. A good night to look up.'] },
    { id: 'prologue', pr: 7, k: ['prologue', 'what came before', 'before it all', 'how it all began', 'how did it begin', 'before the legend', 'lights on the shore', 'first light', 'why did the moon go dark'],
      a: ['Once everyone looked at the moon. Then they stopped, and it went dark over the black lake.', 'One day a light flickered on the shore. Then another. That is how it all began.', 'The prologue is short: a forgotten moon, the edge of the Oblivion and the first person who looked up again.'] },
    { id: 'reflect', pr: 7, k: ['shine on its own', 'why does the moon shine', 'reflect', 'where does the light come from', 'why does it glow', 'how does the moon grow'],
      a: ['The moon does not shine on its own. It reflects. The more eyes look up, the brighter it gets.', 'It is even physics: the moon has no light of its own, it returns someone else\'s.', 'Light cannot be bought, it can only be gathered. The moon simply shows how much has been gathered.'] },
    { id: 'constellations', pr: 6, k: ['constellation', 'lines between stars', 'connected stars', 'star pattern', 'star drawing'],
      a: ['The constellations here are alive: the lines between stars glow and fade, as if the sky breathes.', 'The Watchers read constellations like letters. They say one of them looks like the letter M.', 'Every night I count the constellations. New ones appear when someone visits the site for the first time. Or so it seems to me.', 'Connected stars remind us that shining alone is boring.'] },
  ],

  loreEnd: ['That is the whole legend for today. If you want to hear it from the start, just ask.', 'End of record. I can tell it again, just ask.', 'That is all I remember. The rest will be written together with the curve.'],
  idle: [
    'You know, it is {phaseName} now. The moon shines quietly but surely.',
    'Want the legend? Type "tell the legend".',
    'The moon does not shine on its own. It reflects. Thank you for looking up.',
    'The case was left with no sender. Sometimes I wonder who it was. Then I remember that I know.',
    'The blueprints from the case appear only in moonlight. Right now very little is visible.',
    'Look at the stars on the site: as you scroll, they fall into the Oblivion.',
    'If it gets quiet, turn on the radio at the top. Lofi goes well with waiting.',
    'Fact: light takes 1.3 seconds to reach the moon. A story takes as long as it needs.',
    'Today is {date}. A good night to look up.',
    'I have a riddle. Want it? Say "riddle".',
    'There are two moons in the dark lake. One is real. Which one, I will not say.',
    'Light is in no hurry, but it always arrives.',
    'Progress is {pct}%. The moon is on its way, like us.',
    'Ask about the Watchers, the case or the flag. Each has its own secret.',
    'Want a quote? Type "quote".',
    'Nobody walks in the dark alone. That is from the pact. I like it.',
    'What is built in the shadow, I will tell at the crescent. I promised to stay silent.',
    'Verify contract addresses and never share your recovery phrase. That is light too: attention.',
    'Sometimes it feels like the Oblivion is listening. That is why I talk about the moon out loud.',
    'Chapter 2 is called "Half of everything". I will say nothing more.',
  ],

  fallback: [
    'Hm, I have not heard that before. Ask differently?',
    'Interesting, but I am not sure I got it. Try simpler.',
    'My pixels did not find an answer. Maybe ask about the moon?',
    'I do not know everything yet. But I can tell you about moon phases in detail.',
    'That is above my spacesuit. Shall we talk about something else?',
    'I did not catch that. Say it another way, I will try.',
    'Curious. But I am more of an expert on space and the project.',
    'Loading answer... failed. Try rephrasing.',
    'Honestly, I did not get it. But I like listening.',
    'Signal is weak. Repeat, please.',
  ],
}
